# Generated by Django 4.0.4 on 2022-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Adı Soyadı')),
                ('company', models.CharField(max_length=150, verbose_name='Şirket Adı')),
                ('work', models.CharField(max_length=150, verbose_name='Faaliyet Alanı')),
                ('email', models.CharField(max_length=150, verbose_name='E mail adresi')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefon Numarası')),
                ('message', models.TextField(verbose_name='Mesajı')),
            ],
        ),
    ]
