# Generated by Django 4.0.4 on 2022-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_servicesmodel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='seodescription',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='seotitle',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
