# Generated by Django 4.0.4 on 2022-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category',
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ManyToManyField(to='blogs.category', verbose_name='Kategori Seçin'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.ManyToManyField(to='blogs.tag', verbose_name='Etiket seçin'),
        ),
    ]
