# Generated by Django 4.0.1 on 2022-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogs_category_blogs_category_alter_blogs_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.ManyToManyField(to='blogs.Category', verbose_name='Kategori Seçin'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.ManyToManyField(to='blogs.Tag', verbose_name='Etiket seçin'),
        ),
    ]
