# Generated by Django 4.0.4 on 2022-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_category_alter_blogs_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='seodescription',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='seotitle',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
